### PR TITLE
some css improvements

### PR DESCRIPTION
**Pull request by nicole-chang**
The padding on the dialog boxes still bugs me but other than that...

Changes:
-all dialog boxes have the same style
-user posts and saved posts don't show likes/comments
-some buttons have hover effects
-navbar home button and icon stands out a bit more

### CODE REVIEW

**Comment by tsaomaxwell** [comment]
Why don't you want user and saved posts to have like and comment counts?

**Comment by nicole-chang** [comment]
It's not too bad if the viewing window is really wide, but post thumbnail looks weird when it's squished into a small area like it is in user and saved posts. I didn't have it in the figma design either, but if it's better to have the like and comment counts we can add it back in

**Comment by tsaomaxwell** [comment]
Wouldn't it be better to have conditional formatting on width then?

**Comment by nicole-chang** [comment]
Probably, I didn't think of doing that before

**Pull request merged**
